# Generated by Django 3.1.14 on 2023-01-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xodim', '0003_auto_20230102_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='about',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
