# Generated by Django 3.1.14 on 2023-01-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xodim', '0005_auto_20230102_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='{%url img.user.jpg%}', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(default='Xodim haqida malumot bering!  '),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
