# Generated by Django 3.1.14 on 2023-01-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xodim', '0006_auto_20230103_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
